### ISSUE TITLE
The icons in the power menu are not obvious

### ISSUE THREAD

**Issue by CrossCC** [ukui/ukui-menu#105]
Start menu, the icon in the power options list is black by default, and the display is not obvious
![开始菜单1](https://user-images.githubusercontent.com/33095911/83388610-50852300-a421-11ea-917c-0a8596a529b3.png)

**Comment by CrossCC** [comment]
开始菜单，电源选项列表中的图标默认为黑色，显示不明显

**Comment by Liang-zy** [comment]
20200618 test passed
