### ISSUE TITLE
The mouse pointer slides from the start menu to the start menu button, the start menu will automatically slide down an application

### ISSUE THREAD

**Issue by CrossCC** [ukui/ukui-menu#108]
Version：20.04LTS
ISO：ubuntukylin-20.04-0604-amd64.iso
Test environment：Lenovo ThinkPad-X1-Yoga、Lenovo Thinkpad-T430i

Test steps:
1. Click the start menu button, the mouse slides from the button to the start menu, the start menu list will automatically slide down an application
2. From the start menu to the start menu button, the list will also slide down an application.

测试步骤：
1、点击开始菜单按钮，鼠标从按钮处滑到开始菜单上，开始菜单列表会自动向下滑动一个应用
2、从开始菜单滑到开始菜单按钮处，列表也会向下滑动一个应用。

**Comment by Liang-zy** [comment]
20200618 test passed
