### ISSUE TITLE
Ukui Menu not start

### ISSUE THREAD

**Issue by oltulu** [ukui/ukui-menu#114]
$ ukui-panel
 (0x7ffc93cf6f90) Warning: "Icon Theme not set. Fallbacking to Oxygen, if installed"
 (0x7ffc93cf6f90) Warning: "Fallback Icon Theme (Oxygen) not found"
 (0x7ffc93cf6f90) Debug: configFile is :  ""
 (0x7ffc93cf6f90) Debug: configFile.is not Empty

 (0x7ffc93cf6f90) Debug: desktopDirs  =   ("/home/aylinux/.local/share//ukui/ukui-panel", "/usr/share/ukui/ukui-panel")

 (0x7ffc93cf6f90) Warning: QCoreApplication::postEvent: Unexpected null receiver
 (0x7ffc93cf6f90) Warning: QCoreApplication::postEvent: Unexpected null receiver
 (0x7ffc93cf6f90) Debug: XdgDesktopFile "/usr/share/applications/wps-office-wps.desktop" is not valid
 (0x7ffc93cf6f90) Debug: QLocale::system().name(): "tr_TR"
 (0x7ffc93cf6f90) Debug: showCalendar: 3
 (0x7ffc93cf6f90) Debug: load html----------------------------- "file:///usr/share/ukui-panel/plugin-calendar/html/ukui-solar-en-mon.html"
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: WinIdChange 800007 handle QWidgetWindow(0x55a6b570b730, name="UKUIPanel panel1Window") QScreen(0x55a6b5517260, name="eDP1")
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Warning: QObject::connect: No such signal UKUITaskWidget::clicked()
 (0x7ffc93cf6f90) Warning: QObject::connect:  (receiver name: 'Gtkdialog')
 (0x7ffc93cf6f90) Warning: QObject::connect: No such signal UKUITaskWidget::clicked()
 (0x7ffc93cf6f90) Warning: QObject::connect:  (receiver name: 'Mate-system-monitor')
 (0x7ffc93cf6f90) Warning: QObject::connect: No such signal UKUITaskWidget::clicked()
 (0x7ffc93cf6f90) Warning: QObject::connect:  (receiver name: 'Lxterminal')
 (0x7ffc93cf6f90) Debug: we don't show balloon messages.
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: Unknown property textalignment
 (0x7ffc93cf6f90) Debug: Unknown property textalignment

[aylinux@aylinux ~]$ ukui-menu
[aylinux@aylinux ~]$

**Comment by oltulu** [comment]
https://i.hizliresim.com/ORWD60.png

**Comment by oltulu** [comment]
https://hizliresim.com/dzefKj

**Comment by hepuyao** [comment]
> $ ukui-panel
> (0x7ffc93cf6f90) Warning: "Icon Theme not set. Fallbacking to Oxygen, if installed"
> (0x7ffc93cf6f90) Warning: "Fallback Icon Theme (Oxygen) not found"
> (0x7ffc93cf6f90) Debug: configFile is : ""
> (0x7ffc93cf6f90) Debug: configFile.is not Empty
> 
> (0x7ffc93cf6f90) Debug: desktopDirs = ("/home/aylinux/.local/share//ukui/ukui-panel", "/usr/share/ukui/ukui-panel")
> 
> (0x7ffc93cf6f90) Warning: QCoreApplication::postEvent: Unexpected null receiver
> (0x7ffc93cf6f90) Warning: QCoreApplication::postEvent: Unexpected null receiver
> (0x7ffc93cf6f90) Debug: XdgDesktopFile "/usr/share/applications/wps-office-wps.desktop" is not valid
> (0x7ffc93cf6f90) Debug: QLocale::system().name(): "tr_TR"
> (0x7ffc93cf6f90) Debug: showCalendar: 3
> (0x7ffc93cf6f90) Debug: load html----------------------------- "file:///usr/share/ukui-panel/plugin-calendar/html/ukui-solar-en-mon.html"
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: WinIdChange 800007 handle QWidgetWindow(0x55a6b570b730, name="UKUIPanel panel1Window") QScreen(0x55a6b5517260, name="eDP1")
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Warning: QObject::connect: No such signal UKUITaskWidget::clicked()
> (0x7ffc93cf6f90) Warning: QObject::connect: (receiver name: 'Gtkdialog')
> (0x7ffc93cf6f90) Warning: QObject::connect: No such signal UKUITaskWidget::clicked()
> (0x7ffc93cf6f90) Warning: QObject::connect: (receiver name: 'Mate-system-monitor')
> (0x7ffc93cf6f90) Warning: QObject::connect: No such signal UKUITaskWidget::clicked()
> (0x7ffc93cf6f90) Warning: QObject::connect: (receiver name: 'Lxterminal')
> (0x7ffc93cf6f90) Debug: we don't show balloon messages.
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> (0x7ffc93cf6f90) Debug: Unknown property textalignment
> 
> [aylinux@aylinux ~]$ ukui-menu
> [aylinux@aylinux ~]$

I see "Debug: XdgDesktopFile "/usr/share/applications/wps-office-wps.desktop" is not valid".
What's wrong with your wps ?   Can it click to open？

**Comment by oltulu** [comment]
WPS Office not installed

**Comment by liuhao-startmenu** [comment]
Can you see the menu pop up when you execute the ukui-menu command?

**Comment by oltulu** [comment]
The menu does not open when I run the Ukui-menu command

**Comment by oltulu** [comment]
I prepared a distribution using the Arch Linux based UKUI desktop. But ukui-menu does not work. Can you help with this. I couldn't find the reason

**Comment by liuhao-startmenu** [comment]
Check if there is process information for ukui-menu by executing "ps -axu | grep ukui-menu" command.

**Comment by oltulu** [comment]
[aylinux@aylinux ~]$ ps -axu | grep ukui-menu
aylinux      812  0.4  0.4 459452 33684 ?        Sl   16:42   0:00 /usr/bin/ukui-menu
aylinux     1949  0.0  0.0   6172  2328 pts/0    S+   16:44   0:00 grep ukui-menu
[aylinux@aylinux ~]$

**Comment by handsome-feng** [comment]
It's strange, can you provide the iso you made so that we can test locally?

**Comment by oltulu** [comment]
Aylinux-Ukui iso:  https://dosyayukle.biz/7004e37f95afdf5d

**Comment by oltulu** [comment]
I recompiled all the packages. Ukui-Menu worked
