### ISSUE TITLE
Cannot open vim in start menu

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#13]
系统中未安装vim包，但开始菜单中存在vim程序，且无法打开

The vim package is not installed in the system, but the vim program exists in the start menu and cannot be opened

**Comment by xiaodongliu-nudt** [comment]
invalid in version 20200327

**Comment by liumin0322** [comment]
20200615 version test failed

**Comment by liumin0322** [comment]
20200615 version test failed

**Comment by Liang-zy** [comment]
20200618 test   faild

**Comment by liuhao-startmenu** [comment]
vim没有安装

**Comment by Liang-zy** [comment]
> vim没有安装
我没有安装-那开始菜单应该没有，为什么会有？

**Comment by liuhao-startmenu** [comment]
vim-common提供vim.desktop文件

**Comment by liumin0322** [comment]
20200717 test passed
