### ISSUE TITLE
"Add to desktop shortcut" feature does not work

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#17]
开始菜单中，右键选择“添加到桌面快捷方式”，无效

In the start menu, right click and select "Add to desktop shortcut", it has no effect

**Comment by xiaodongliu-nudt** [comment]
@liuhao-startmenu 当前麒麟助手 右键选择“添加到桌面快捷方式”时，桌面图标不正确

**Comment by liuhao-startmenu** [comment]
需要和桌面联调

**Comment by liuhao-startmenu** [comment]
@Yue-Lan

**Comment by liumin0322** [comment]
20200717 test passed
