### ISSUE TITLE
[Suggestion] The corresponding initial letter list can be selected through the keyboard

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#18]
建议：在开始菜单中，可通过键盘选择相应首字母列表

Suggestion: In the start menu, you can select the corresponding initial letter list by keyboard

**Comment by xiaodongliu-nudt** [comment]
Useful suggestion

**Comment by liuhao-startmenu** [comment]
支持首字母搜索

**Comment by Liang-zy** [comment]
20200618 test passed
