### ISSUE TITLE
menuwin has no attribute mainwin 16.10

### ISSUE THREAD

**Issue by ghost** [ukui/ukui-menu#2]
On ubuntu mate 16.10
/usr/lib/ukui-menu/ukui-menu.py"Traceback (most recent call last):   File "/usr/lib/ukui-menu/ukui-menu.py", line 352, in showMenu     self.toggleMenu()   File "/usr/lib/ukui-menu/ukui-menu.py", line 364, in toggleMenu     self.positionMenu()   File "/usr/lib/ukui-menu/ukui-menu.py", line 369, in positionMenu     ourWidth  = self.mainwin.window.get_size()[0] AttributeError: 'MenuWin' object has no attribute 'mainwin

**Comment by handsome-feng** [comment]
Hi, bluedxca93, Download the latest version of ukui-menu will run well in ubuntu mate.

**Comment by cinnamoner** [comment]
@handsome-feng Oops! I missed this although I know bluedxca93. Wow, so the latest UKUI menu runs on Mate without problems? What about the search bug? Has it been sorted out?
***
I apologize but I've got virtually no experience with Mate. The reason has always been the lack of a good and preferably windowsy startmenu. Seems things are changing. Again, I like UKUI menu better than Brisk. I'm definitely not crossing over to Mate because of Brisk. But I might be crossing over to Mate because of UKUI menu. And that's that.

**Comment by ghost** [comment]
Hi, @handsome-feng I really don't wanna bug you but I think the UKUI startmenu also works on Linux Mint Mate. Am I right?

**Comment by handsome-feng** [comment]
@cinnamoner Sorry, but there are some problems when running on Linux Mint Mate, It may be related to the gtk version, I will check this whenever I'm free.

**Comment by ghost** [comment]
@handsome-feng Thanks. Crossed my mind to run it on Mint but I've changed my mind. I will run it on Ubuntu Mate. Or even better, I'll wait for Ubuntu Kylin with the UKUI. Anyways, compatibility with Ubuntu Mate should be preserved. Again, thank you very much 👍

**Comment by ghost** [comment]
@handsome-feng Just crossed my mind: it would be useful to post an image, illustrating the UKUI menu. It will make even more popular and known.

**Comment by handsome-feng** [comment]
@cinnamoner  Thank you for your suggestion, I have posted an image for the moment, but it is a litter fuzzy, I will update this later.

**Comment by ghost** [comment]
> I have posted an image for the moment, but it is a litter fuzzy, I will update this later.

@handsome-feng I've seen it, yes. No worries, I understand you're concentrating on development right now.

**Comment by ghost** [comment]
@handsome-feng no menu on ubuntu  16.10  mate. errors not visible now.

**Comment by ghost** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/4351663/23661062/63aa36dc-0343-11e7-9be7-2de6d6a7a5ff.png)
Just opened the other menu to show you what works.

**Comment by handsome-feng** [comment]
@bluedxca93  Sorry, but I don't understand what you mean, I see the ukui-menu on the right of the panel, does it can't open?

**Comment by ghost** [comment]
👀

**Comment by ghost** [comment]
@handsome-feng yes. the error warnings are now gone but not opening
while clicking on it.

**Comment by ghost** [comment]
maybe its related to the mate version.what is the mate release ukui is based on?

**Comment by ghost** [comment]
Forked from rather than based on. @bluedxca93 Thanks for putting effort into it. I'm following with interest. I'm interested in the menu but I'm also interested in the whole UKUI.

**Comment by cinnamoner** [comment]
@bluedxca93 While I was beholdin your screenshot, I recalled something I had seen on Open Desktop. I'm posting the link shortly, but not here.

**Comment by handsome-feng** [comment]
@bluedxca93: Can you post your /var/log/syslog after you clicked the ukui-menu ?

**Comment by ghost** [comment]
@handsome-feng I have a Debian stable (Jessie) with inbuilt remastering tool. I wonder whether I could pull in the whole UKUI. It's a nice desktop.

**Comment by handsome-feng** [comment]
@cinnamoner  The UKUI has not in the Debian archive yet, so you could not pull the whole UKUI through 'apt-get install ukui-desktop-environment'. Plus, we did not test on Jessie, so far the best way to try UKUI is using ubuntu/ubuntukylin/ubuntumate 1704. Thank you!

**Comment by maclin0211** [comment]
@cinnamoner  we will try to push UKUI into Debian later.  It may take a long time. There is a lot of work we have to do for that.

**Comment by ghost** [comment]
@handsome-feng @maclin0211 Thank you guys.

**Comment by ghost** [comment]
@bluedxca93 You never answered. I'm still very much interested in UKUI menu. And Tilo menu.
