### ISSUE TITLE
在开始菜单右键之后选择属性没有响应

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/ukui-menu#21]
打开开始菜单之后在一个项目上右键，选择属性没有响应，不会弹出来对应的弹窗

**Comment by liuhao-startmenu** [comment]
设计思路是调用文件管理器属性功能，需要兰悦协助解决。

**Comment by xiaodongliu-nudt** [comment]
@Yue-Lan 协助看下这个问题

**Comment by Yue-Lan** [comment]
如果想打开peony的属性界面，可以通过peony实现的org.freedesktop.FileManager1 dbus服务的showProerties接口，或者查看peony的man手册，通过命令行调用打开对应窗口。

我不推荐通过文件管理器查看应用属性，因为应用属性只是一个desktop文件而已。除非你愿意为文件管理器写一个应用属性页面的插件，否则你得不到想要的结果。

**Comment by xiaodongliu-nudt** [comment]
@liuhao-startmenu 开始菜单中右键-》属性跟桌面相应快捷方式右键-》属性是同样效果吗？

**Comment by Liang-zy** [comment]
20200618 test passed  :  This feature is currently canceled
