### ISSUE TITLE
开始菜单的控制面板快捷方式不能使用

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/ukui-menu#22]
开始菜单的控制面板快捷方式不能使用，打不开控制面板，单独开启是可以的

**Comment by liuhao-startmenu** [comment]
控制面板没有提供.desktop文件，需要贺冰协助解决。

**Comment by smiley286** [comment]
the file ukui-control-center.desktop had already provided

**Comment by liumin0322** [comment]
20200309版本测试通过
