### ISSUE TITLE
开始菜单点击用户显示的控制面板

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/ukui-menu#23]

**Comment by liumin0322** [comment]
左击“用户头像”图标，弹出控制面板窗口
Control panel window pops up after left-clicking the "user avatar" icon

**Comment by liuhao-startmenu** [comment]
设计逻辑是跳转到控制面板用户设置界面，需要贺冰协助解决。

**Comment by Liang-zy** [comment]
The 20200410 version passed the test
