### ISSUE TITLE
开始菜单中，左击“我的电脑”和“设置”，无响应

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#24]
Left-click on My Computer and Settings in the Start menu are unresponsive

**Comment by liuhao-startmenu** [comment]
1.“我的电脑”启动命令被修改导致点击无响应；
2.  控制面板没有提供.desktop文件，导致点击“设置”无响应。

**Comment by liumin0322** [comment]
20200302版本测试通过
