### ISSUE TITLE
右击“我的电脑”和“设置”图标，选择“固定到任务栏”，弹出Drop Error报错提示

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#25]
Right-click the "My Computer" and "Settings" icons and select "Pin to Taskbar", a Drop Error error message pops up

**Comment by liumin0322** [comment]
右键点击“我的电脑”，选择“固定到任务栏”，弹出Drop Error报错

**Comment by liuhao-startmenu** [comment]
需要我的电脑和设置提供.desktop文件

**Comment by xiaodongliu-nudt** [comment]
@liuhao-startmenu 
我的电脑：peony-computer.desktop
设置：ukui-control-center.desktop

**Comment by Liang-zy** [comment]
The 20200410 version passed the test
