### ISSUE TITLE
Please, Add to Korean Language

### ISSUE THREAD

**Issue by MoorDev** [ukui/ukui-menu#3]
[UKUI-Menu_ko.po.zip](https://github.com/ukui/ukui-menu/files/1022580/UKUI-Menu_ko.po.zip)

Hello, UKUI dev Team.
I am Korean user. So, I translate to po file for Korean. I want to this translation add to source tree. But, I don't know that how to merge. 

Please, This translation add to source tree. Thanks.

**Comment by handsome-feng** [comment]
Hi, @MoorDev Thank you! I have merged this.  :+1:
