### ISSUE TITLE
在开始菜单中，点击”打印机“程序，系统卡死

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#31]
In the Start menu, click on the "Printer" program, the system crashes

**Comment by CrossCC** [comment]
补充说明：
先打开top查看进程，点击”打印机“之后发现打印机进程占用CPU达到100%，过一会之后，出现打印机界面，CPU占用率降低。点击打印机界面任意按钮，又卡死，之后闪退。

**Comment by moshengrenzenme** [comment]
补充说明，这是上游的软件bug，不是这个组件的问题

**Comment by liumin0322** [comment]
20200309版本测试通过
