### ISSUE TITLE
can't find Software and Update

### ISSUE THREAD

**Issue by dou-y** [ukui/ukui-menu#33]
In the menu, I can't find Software and Update which can be used to change update option.
<img width="915" alt="图片" src="https://user-images.githubusercontent.com/59866026/74813226-f9ef4f80-532f-11ea-893e-728f7a43b82c.png">
This is been installed already. In fact if I enter `software-properties-gtk` in termitor, this can be display.
<img width="1163" alt="图片" src="https://user-images.githubusercontent.com/59866026/74813670-a6c9cc80-5330-11ea-9158-3ce5b7380089.png">

**Comment by xiaodongliu-nudt** [comment]
20200320版本通过
