### ISSUE TITLE
偶发性的窗口被遮住了（不确定是偶发还是必然，我能百分百触发）

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/ukui-menu#37]
![IMG_20200306_013838](https://user-images.githubusercontent.com/33083187/76009788-beb66880-5f4c-11ea-8746-d08ae0204302.jpg)
我打开火狐之后，把火狐全屏，然后恢复窗口，这个时候如果点击开始菜单，开始菜单会被恢复之后的火狐遮住，我这里是百分百复现

**Comment by liumin0322** [comment]
20200309版本测试通过
