### ISSUE TITLE
全屏模式下关闭，再次打开仍为全屏

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#40]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200309-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开开始菜单，点击全屏按钮
2、滑动至应用底部
3、点击2次开始菜单按钮，关闭并再次打开开始菜单

预期结果：显示为左下角默认态

实际结果：显示为全屏模式，且应用快速滑动至顶部

**Comment by xiaodongliu-nudt** [comment]
按照设计，系统初始默认是半屏状态。同时可在控制面板里进行设置，设为全屏，以后每次都是全屏。

**Comment by xiaodongliu-nudt** [comment]
20200320版本通过
