### ISSUE TITLE
开始菜单空白处右键后，弹出异常右键菜单，导致开始菜单崩溃

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#41]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、在开始菜单空白处，右键点击，弹出异常菜单
2、左键点击后，异常菜单消失
3、在桌面右键点击，出现异常右键菜单
4、再次右键点击，桌面右键正常
5、点击开始菜单

预期结果：正常

实际结果：第5步开始菜单无响应

**Comment by liuhao-startmenu** [comment]
任务栏屏蔽鼠标右键后出现的问题，需要联调

**Comment by xiaodongliu-nudt** [comment]
@hepuyao 一起看下问题

**Comment by liumin0322** [comment]
20200402-beta版本测试通过。
