### ISSUE TITLE
在menu上右键点击以后，在其他的位置左键点击后，menu依旧高亮

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/ukui-menu#43]
在menu上右键点击以后，在其他的位置左键点击后，让弹出菜单消失，menu依旧高亮，而且右键调出了panel的菜单，menu也还是高亮
![2020-03-15 01-39-33屏幕截图](https://user-images.githubusercontent.com/33083187/76687332-dcc34d80-665d-11ea-8ef3-28c77c44f3f1.png)

**Comment by xiaodongliu-nudt** [comment]
目前开始菜单在显示之后，貌似只能通过点按钮才能消失，左键单击屏幕其他位置好像不能消失，这个设计不合理。

**Comment by liuhao-startmenu** [comment]
任务栏屏蔽鼠标右键之后出现的问题，需要联调

**Comment by xiaodongliu-nudt** [comment]
@hepuyao 一起看下这个问题

**Comment by liumin0322** [comment]
Tested fail in the 20200418 version

**Comment by Liang-zy** [comment]
20200618 test passed
