### ISSUE TITLE
注销后登录，需点击2次后打开

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#44]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、注销后登录
2、点击任务栏中开始菜单图标

预期结果：点击一次，即可成功弹出开始菜单

实际结果：需点击2次后打开

**Comment by xiaodongliu-nudt** [comment]
20200320版本测试未通过

**Comment by liumin0322** [comment]
20200328版本测试通过。
