### ISSUE TITLE
打开开始菜单-点击电源，再点击开始菜单，开始菜单-收回，电源弹出菜单没有收回 

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#51]

**Comment by xiaodongliu-nudt** [comment]
而且当开始菜单收回但电源菜单未收回时，再次点击开始菜单，开始菜单会无法弹出。
貌似该问题同issue #50 有关联，当发生issue #50 时，大概率会出现本issue。

**Comment by liumin0322** [comment]
Tested pass in the 20200418 version
