### ISSUE TITLE
My system can't display the ukui-menu menu

### ISSUE THREAD

**Issue by runpython** [ukui/ukui-menu#6]
System version: 17.04
erro:
Dec 29 09:24:16 run24pro-ThinkPad-X230 org.mate.panel.applet.UkuiMenuAppletFactory[1152]:   File "/usr/lib/ukui-menu/ukui-menu.py", line 47
I can't find the help of the problem. Thank you.

**Comment by penghuanmail** [comment]
Please show me your /var/log/syslog output , the code of line 47 is "except Exception, e:", which python version you use?

**Comment by runpython** [comment]
Yes, I'm using python3.5
syslog:
Dec 29 10:23:40 run24pro-ThinkPad-X230 dbus-daemon[1153]: Activating service name='org.mate.panel.applet.UkuiMenuAppletFactory'
Dec 29 10:23:40 run24pro-ThinkPad-X230 org.mate.panel.applet.UkuiMenuAppletFactory[1153]:   File "/usr/lib/ukui-menu/ukui-menu.py", line 47
Dec 29 10:23:40 run24pro-ThinkPad-X230 org.mate.panel.applet.UkuiMenuAppletFactory[1153]:     except Exception, e:
Dec 29 10:23:40 run24pro-ThinkPad-X230 org.mate.panel.applet.UkuiMenuAppletFactory[1153]:                     ^
Dec 29 10:23:40 run24pro-ThinkPad-X230 org.mate.panel.applet.UkuiMenuAppletFactory[1153]: SyntaxError: invalid syntax
Dec 29 10:23:40 run24pro-ThinkPad-X230 dbus-daemon[1153]: Activated service 'org.mate.panel.applet.UkuiMenuAppletFactory' failed: Process org.mate.panel.applet.UkuiMenuAppletFactory exited with status 1
Dec 29 10:23:40 run24pro-ThinkPad-X230 dbus-daemon[1153]: Activating service name='org.mate.panel.applet.WnckletFactory'
Dec 29 10:23:40 run24pro-ThinkPad-X230 dbus-daemon[1153]: Activating service name='org.mate.panel.applet.MateIndicatorsAppletFactory'
Dec 29 10:23:40 run24pro-ThinkPad-X230 dbus-daemon[1153]: Successfully activated service 'org.mate.panel.applet.WnckletFactory'
Dec 29 10:23:40 run24pro-ThinkPad-X230 dbus-daemon[1153]: Successfully activated service 'org.mate.panel.applet.MateIndicatorsAppletFactory'
Dec 29 10:23:42 run24pro-ThinkPad-X230 kernel: [   17.135739] random: crng init done
Dec 29 10:23:42 run24pro-ThinkPad-X230 dbus-daemon[1153]: Activating service name='org.gnome.ScreenSaver'
Dec 29 10:23:42 run24pro-ThinkPad-X230 dbus-daemon[1153]: Successfully activated service 'org.gnome.ScreenSaver'
Dec 29 10:23:46 run24pro-ThinkPad-X230 ModemManager[507]: <info>  Creating modem with plugin 'Generic' and '1' ports
Dec 29 10:23:46 run24pro-ThinkPad-X230 ModemManager[507]: <warn>  Could not grab port (tty/ttyS4): 'Cannot add port 'tty/ttyS4', unhandled serial type'
Dec 29 10:23:46 run24pro-ThinkPad-X230 ModemManager[507]: <warn>  Couldn't create modem for device at '/sys/devices/pci0000:00/0000:00:16.3': Failed to find primary AT port
Dec 29 10:24:03 run24pro-ThinkPad-X230 whoopsie[1115]: [10:24:03] Not online; processing later (/var/crash/_usr_lib_ukui-menu_ukui-menu.py.1001.crash).
Dec 29 10:24:09 run24pro-ThinkPad-X230 dbus-daemon[1153]: Activating via systemd: service name='org.gnome.Terminal' unit='gnome-terminal

**Comment by penghuanmail** [comment]
Now ukui-menu can only support python2, we will port to python3 in 18.04

**Comment by runpython** [comment]
thanks penghuanmail
What do I have to do now？Delete python3？

**Comment by penghuanmail** [comment]
do you have python2 in your system?

**Comment by runpython** [comment]
yes

**Comment by penghuanmail** [comment]
try to install python-minimal

**Comment by runpython** [comment]
thanks!penghuanmail.
