### ISSUE TITLE
【双屏模式】开始菜单全屏模式显示异常

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#60]

**Comment by liumin0322** [comment]
![2020-03-20 20-17-17屏幕截图](https://user-images.githubusercontent.com/48200161/77162913-fe05bd00-6ae7-11ea-9816-0fedb67d468c.png)

**Comment by moshengrenzenme** [comment]
双屏模式建议开发者让menu只显示在主屏幕上，不要放大到双屏

**Comment by liumin0322** [comment]
20200328版本测试通过。
