### ISSUE TITLE
右键点击开始菜单-显示不全

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-menu#67]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200320-amd64.iso
测试环境：联想启天M415-N000台式机
测试步骤：
1.系统语言为英语
2.桌面鼠标单击开始菜单

预期结果：电源信息显示正常
实际结果：电源信息显示不全

**Comment by liuhao-startmenu** [comment]
何朴尧负责处理

**Comment by xiaodongliu-nudt** [comment]
@hepuyao 关注一下这个问题

**Comment by liumin0322** [comment]
Tested pass in the 20200418 version
