### ISSUE TITLE
鼠标右键点击开始菜单-关闭计算机显示不全

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-menu#68]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200320-amd64.iso
测试环境：联想启天M415-N000台式机
测试步骤：
1.系统语言为中文
2.桌面右键点击开始菜单

预期结果： 电源信息显示正常
实际结果：关闭计算机显示不全

**Comment by xiaodongliu-nudt** [comment]
Duplicate of #67
