### ISSUE TITLE
快速搜索

### ISSUE THREAD

**Issue by wi24rd** [ukui/ukui-menu#7]
想要快速启动想要的应用，也就是按下 super 键后输入文字的同时菜单里能及时匹配文本框文字的应用。然而通常使用过一次之后，再次按下 super 键并不能像上次一样进行搜索，此时输入文字没有反应。需要再次按下 super 键将菜单关闭再按下 super 键重新打开菜单才能继续搜索。不知道是刻意如此设计还是程序本身存在问题？希望能修复。
环境为 Ubuntu Kylin 17.10 x86_64。主题、字体、窗口管理器等都没有更改。

**Comment by handsome-feng** [comment]
感谢你的反馈, 这个问题我们会尽快修复(不过应该在年后了 :) )

**Comment by handsome-feng** [comment]
你好, 问题已修复, 不过由于现在github上的代码是基于python3的了, 你不能直接将现在的项目编译安装,在17.10上你可以使用我的patch来立即修复:
补丁下载地址:
https://pan.baidu.com/s/1nw4ozhB
使用方法:
sudo patch /usr/lib/python2.7/dist-packages/ukui_menu/plugins/menu.py fix_focus.patch
