### ISSUE TITLE
开始菜单全屏模式下，拖动应用后，会复制多个，且可随意摆放位置

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#70]

**Comment by liumin0322** [comment]
![2020-03-28 17-50-49屏幕截图](https://user-images.githubusercontent.com/48200161/77820391-ec8e6780-711c-11ea-8a89-7f5e532f291e.png)

**Comment by Liang-zy** [comment]
The 20200410 version passed the test
