### ISSUE TITLE
【国际化】电源中首字母均应大写，另部分翻译不正确

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#76]
注销应为Logout

![Screenshot from 2020-04-03 16-28-59](https://user-images.githubusercontent.com/48200161/78340366-90b65980-75c8-11ea-838c-5c1b4e07f301.png)

**Comment by liuhao-startmenu** [comment]
参照win10电源右键菜单设计

**Comment by Yue-Lan** [comment]
Translating: [Internationalization] The first letter of the power supply should be capitalized, and the other part is incorrectly translated.

**Comment by Liang-zy** [comment]
The 20200508 version passed the test
