### ISSUE TITLE
【双屏扩展】主屏在右，扩展屏在左的情况下，开始菜单显示位置异常

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#78]
![2020-04-04 17-31-17屏幕截图](https://user-images.githubusercontent.com/48200161/78423919-5ae2a500-769c-11ea-907e-5d7fae673b2c.png)

**Comment by Yue-Lan** [comment]
Translating: [Dual screen expansion] When the expansion screen is on and the main screen is down, the start menu display position is abnormal.

**Comment by liumin0322** [comment]
test passed in the 20200418
