### ISSUE TITLE
【双屏扩展】扩展屏在上，主屏在下的情况下，开始菜单显示位置异常 

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#79]
![2020-04-04 19-50-13屏幕截图](https://user-images.githubusercontent.com/48200161/78449973-d13bd300-76ad-11ea-8a2b-4c84337bb9d6.png)

**Comment by Yue-Lan** [comment]
Translating: [Dual screen expansion] When the expansion screen is on and the main screen is down, the start menu display position is abnormal.

**Comment by liumin0322** [comment]
test failed in the 20200418

**Comment by Liang-zy** [comment]
20200618 test passed
