### ISSUE TITLE
[Full Screen] The font on the right is very small.

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-menu#80]
![2020-04-08 14-53-52屏幕截图](https://user-images.githubusercontent.com/48200161/78753789-05aed800-79a9-11ea-8323-3d9d9fc43615.png)

**Comment by Yue-Lan** [comment]
Translating: [Full Screen] The font on the right is very small.

**Comment by liumin0322** [comment]
test passed in the 20200418
