### ISSUE TITLE
 ukui-menu  UKUI-Kwin won't open

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-menu#81]
Version: 20.04LTS
Iso: ubuntukylin-ukui3.0-20200410-amd64.iso
Test environment: Lenovo Qitian M415-N000 desktop
Test steps:
1. Start Menu-Click on UKUI-Kwin
2.
Expected result: can be opened
Actual result: no response

**Comment by xiaodongliu-nudt** [comment]
The UKUI-Kwin icon should not appear in the menu. @liuhao-startmenu

**Comment by Liang-zy** [comment]
The 20200508 version passed the test
