### ISSUE TITLE
[suggestion] Add "Control Panel" entry to all software in the start menu

### ISSUE THREAD

**Issue by CrossCC** [ukui/ukui-menu#87]
Control Panel--Personalization--Desktop--The icon locked in the start menu, the lock of the setting button is not turned on, there is no direct entry to the control panel in the system, only by changing the wallpaper or adjusting the volume and other purposeful settings control panel.

**Comment by ikeyhzj** [comment]
Once the control panel is closed at its fixed location in the start menu, normal users cannot find the control panel

**Comment by Liang-zy** [comment]
20200528 test passed
